# Generated by Django 4.1 on 2023-04-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0025_alter_doctor_doctor_id_alter_patient_patient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Image_URL',
            field=models.CharField(default='default', max_length=400),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.IntegerField(default=86719, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(default=50502, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.IntegerField(default=46205, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
