# Generated by Django 4.1 on 2023-04-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0028_alter_doctor_doctor_id_alter_patient_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.IntegerField(default=32469, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(default=41130, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.IntegerField(default=11752, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
