# Generated by Django 4.1 on 2023-04-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0031_alter_doctor_doctor_id_alter_report_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.IntegerField(default=35959, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.IntegerField(default=17303, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
