# Generated by Django 4.1 on 2023-04-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0033_alter_doctor_doctor_id_alter_doctor_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.IntegerField(default=78830, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.IntegerField(default=68328, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
