# Generated by Django 4.1 on 2023-04-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0035_alter_doctor_doctor_id_alter_report_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='disease_name',
            field=models.CharField(choices=[('Pneumonia', 'Pneumonia'), ('Malaria', 'Malaria'), ('Brain Cancer', 'Brain Cancer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
